Repository ConanGH-S/practicas-ctm, pull requests merged in 2023-07, with the labels that each got.

#63 get class by number by query request
  server/src/controllers/classes.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/db/db.sql
  server/src/middlewares/classes.middlewares.ts
  server/src/middlewares/users.middlewares.ts
Labels: API

#71 DB up to date
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/db/db.sql
  server/src/middlewares/classes.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
Labels: enhancement, database

#72 Refactor student
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/roles.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/db/db.sql
Labels: bug, database, API

#73 Create user fixed
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Assign-class/AssignClass.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Siderbar/Sidebar.jsx
  client/src/components/TeacherTest/TeacherTest.jsx
  client/src/components/Teachers/Teachers.jsx
  client/src/components/User/User.jsx
  client/src/components/Visits/Visits.jsx
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/middlewares/practicalStages.middlewares.ts
Labels: bug, database, API

#74 Update README.md
  README.md
Labels: enhancement

#77 API REST v3.0.0
  server/package.json
  server/src/app.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/students.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/db/db.sql
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/middlewares/users.middlewares.ts
  server/src/routes/routes.ts
  server/src/routes/student.routes.ts
  server/src/routes/users.routes.ts
Labels: enhancement, database, API

#80 Create students route works
  server/package.json
  server/src/config/db.ts
  server/src/controllers/students.controllers.ts
  server/src/errors/customErrors.ts
  server/src/interfaces/students.interfaces.ts
  server/src/middlewares/inscriptions.middlewares.ts
  server/src/middlewares/roles.middlewares.ts
  server/src/middlewares/students.middlewares.ts
  server/src/models/errorCodes.enums.ts
  server/src/routes/routes.ts
  server/src/routes/students.routes.ts
  server/src/schemas/students.schemas.ts
Labels: enhancement, API

#81 feat(server): v3.2.0 | detailInfoStudent route add
  README.md
  server/package.json
  server/src/controllers/students.controllers.ts
  server/src/routes/students.routes.ts
Labels: enhancement, API

#85 docs: updated docs
  docs/Documentos técnicos e informales/Diagrama de flujo
  docs/Documentos técnicos e informales/Documento sin título.docx
  docs/Documentos técnicos e informales/Justificación del proyecto.docx
  docs/Documentos técnicos e informales/Requisitos funcionales.docx
  docs/Manual de usuario/Manual de Usuarios.docx
Labels: documentation

#84 Loren rama
  client/package.json
  client/src/app/rolesSlice.js
  client/src/app/store.js
  client/src/components/Assign-class/AssignClass.jsx
  client/src/components/Bitacoras/Bitacoras.jsx
  client/src/components/Form/Form.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Siderbar/Sidebar.jsx
  client/src/components/Student/Student.jsx
  client/src/components/Teachers/Teachers.jsx
  client/src/components/User/User.jsx
  client/src/components/Utils/Button/Button.jsx
  client/src/components/Utils/Pagination/Pagination.jsx
  client/src/import/staticData.jsx
  client/src/main.jsx
  client/tailwind.config.js
  docs/Actas/Acta No. 1 - 19 Mayo.pdf
  docs/Actas/Acta No. 2 - 13 Junio.pdf
  docs/Actas/Acta No. 3 - 18 Julio.pdf
  docs/Actas/Acta No. 4 - 25 Julio.pdf
  server/src/controllers/practicalStages.controllers.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/middlewares/users.middlewares.ts
Labels: documentation, enhancement, client

#86 feat: student name card details
  server/src/controllers/students.controllers.ts
  server/src/routes/students.routes.ts
Labels: API
