Repository ConanGH-S/practicas-ctm, pull requests merged in 2023-06, with the labels that each got.

#10 Scroll behavior
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/public/user.png
  client/public/vite.svg
  client/src/App.jsx
  client/src/assets/react.svg
  client/src/components/Button/Button.jsx
  client/src/components/Card/Card.jsx
  client/src/components/Form/Form.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Siderbar/Sidebar.jsx
  client/src/components/User/User.jsx
  client/src/index.css
  client/tailwind.config.js
  server/.gitignore
  server/.vscode/settings.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/roles.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/middlewares/users.middlewares.ts
  server/src/models/PracticalStages.interfaces.ts
  server/src/models/httpStatus.enums.ts
  server/src/models/inscriptions.interfaces.ts
  server/src/models/user.interfaces.ts
  server/src/routes/inscriptions.routes.ts
  server/src/routes/practicalStages.routes.ts
  server/src/routes/roles.routes.ts
  server/src/routes/routes.ts
Labels: enhancement, help wanted

#31 Classes routes
  server/src/app.ts
  server/src/controllers/classes.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/interfaces/classes.interfaces.ts
  server/src/middlewares/classes.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/models/errorCodes.enums.ts
  server/src/routes/classes.routes.ts
  server/src/routes/routes.ts
  server/src/schemas/classes.schemas.ts
Labels: enhancement

#32 Classes routes
  server/src/controllers/classes.controllers.ts
  server/src/routes/classes.routes.ts
Labels: enhancement

#38 Register student
  client/package.json
  client/src/components/Card/Card.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/Siderbar/Sidebar.jsx
  client/src/components/Student/Student.jsx
  client/src/components/Utils/Modals/Modals.jsx
  client/src/components/Visits/Visits.jsx
  client/src/import/staticData.jsx
  client/src/validation/inscriptionsValidation.js
  client/tailwind.config.js
  server/src/config/config.js
  server/src/config/db.js
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/tsconfig.json
Labels: enhancement

#39 Added get student by name
  server/src/controllers/users.controllers.ts
  server/src/middlewares/users.middlewares.ts
  server/src/routes/users.routes.ts
Labels: enhancement

#41 Update README.md
  README.md
Labels: help wanted

#43 db updated
  server/src/db/db.sql
Labels: help wanted

#44 editInscription added, was erased
  server/.vscode/settings.json
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/middlewares/practicalStages.middlewares.ts
Labels: bug, enhancement

#46 Update README.md
  README.md
Labels: enhancement

#47 db admin user updated
  server/src/db/db.sql
Labels: enhancement, good first issue

#54 apprentice search bug fixed
  client/src/components/Student/Student.jsx
  client/src/readExcelFile/reactExcelFile.jsx
Labels: UX

#55 get user by name change to req.query
  server/src/controllers/users.controllers.ts
  server/src/middlewares/users.middlewares.ts
  server/src/routes/users.routes.ts
Labels: server, API

#56 Get user by name
  server/src/app.ts
  server/src/controllers/changeStatusId.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/interfaces/changeStatusId.interfaces.ts
  server/src/middlewares/changeStatusId.middlewares.ts
  server/src/routes/changeStatusId.routes.ts
  server/src/routes/routes.ts
  server/src/schemas/changeStatusId.schemas.ts
Labels: server, API

#59 Updated Database
  client/package-lock.json
  client/package.json
  client/src/components/Form/Form.jsx
  client/src/components/Register-student/RegisterStudent.jsx
  client/src/components/User/User.jsx
  client/src/components/Visits/Visits.jsx
  client/src/mapeo/Map.jsx
  client/src/readExcelFile/reactExcelFile.jsx
  client/src/validation/RegularExpressions.js
  server/src/config/config.ts
  server/src/config/db.ts
  server/src/controllers/classes.controllers.ts
  server/src/controllers/inscriptions.controllers.ts
  server/src/controllers/practicalStages.controllers.ts
  server/src/controllers/roles.controllers.ts
  server/src/controllers/users.controllers.ts
  server/src/db/db.sql
  server/src/errors/customErrors.ts
  server/src/middlewares/inscriptions.middlewares.ts
  server/src/middlewares/practicalStages.middlewares.ts
  server/src/middlewares/roles.middlewares.ts
  server/src/models/httpStatus.enums.ts
  server/src/routes/inscriptions.routes.ts
  server/src/routes/users.routes.ts
Labels: database
